import cron from 'node-cron';
import axios from 'axios';
import dotenv from 'dotenv';
import { SubtitleCorrection, TrainingBatch, ModelVersion } from '../models/index.js';
import redis from '../config/redis.js';

dotenv.config();

const ALGORITHM_SERVICE_URL = process.env.ALGORITHM_SERVICE_URL || 'http://algorithm:8000';
const MIN_TRAINING_SAMPLES = parseInt(process.env.MIN_TRAINING_SAMPLES || '100');
const TRAINING_CRON_SCHEDULE = process.env.TRAINING_CRON_SCHEDULE || '0 2 * * 0';
const TRAINING_LOCK_KEY = 'training:lock';
const TRAINING_LOCK_TTL = 3600;

class SchedulerService {
  constructor() {
    this.trainingJob = null;
    this.isRunning = false;
  }

  start() {
    if (this.trainingJob) {
      console.log('[Scheduler] Training job already running');
      return;
    }

    console.log(`[Scheduler] Starting training scheduler with schedule: ${TRAINING_CRON_SCHEDULE}`);
    
    this.trainingJob = cron.schedule(TRAINING_CRON_SCHEDULE, async () => {
      console.log('[Scheduler] Cron trigger: checking for training');
      await this.checkAndScheduleTraining();
    }, {
      scheduled: true,
      timezone: 'Asia/Shanghai'
    });

    this.trainingJob.start();
    console.log('[Scheduler] Training scheduler started successfully');
  }

  stop() {
    if (this.trainingJob) {
      this.trainingJob.stop();
      this.trainingJob = null;
      console.log('[Scheduler] Training scheduler stopped');
    }
  }

  async acquireLock() {
    const result = await redis.set(TRAINING_LOCK_KEY, '1', 'EX', TRAINING_LOCK_TTL, 'NX');
    return result === 'OK';
  }

  async releaseLock() {
    await redis.del(TRAINING_LOCK_KEY);
  }

  async checkAndScheduleTraining() {
    if (this.isRunning) {
      console.log('[Scheduler] Training already in progress, skipping');
      return;
    }

    const lockAcquired = await this.acquireLock();
    if (!lockAcquired) {
      console.log('[Scheduler] Could not acquire training lock, skipping');
      return;
    }

    try {
      this.isRunning = true;
      console.log('[Scheduler] Starting training check');

      const unusedCorrections = await SubtitleCorrection.findAll({
        where: { isUsedForTraining: false },
        order: [['createdAt', 'ASC']]
      });

      console.log(`[Scheduler] Found ${unusedCorrections.length} unused corrections`);

      if (unusedCorrections.length < MIN_TRAINING_SAMPLES) {
        console.log(
          `[Scheduler] Insufficient samples: ${unusedCorrections.length}/${MIN_TRAINING_SAMPLES}. ` +
          `Need ${MIN_TRAINING_SAMPLES - unusedCorrections.length} more.`
        );
        return;
      }

      const existingModels = await ModelVersion.findAll({
        order: [['createdAt', 'DESC']],
        limit: 1
      });

      const latestVersion = existingModels[0]?.version || 'v1.0.0';
      const versionParts = latestVersion.match(/v(\d+)\.(\d+)\.(\d+)/);
      
      let newVersion;
      if (versionParts) {
        const major = parseInt(versionParts[1]);
        const minor = parseInt(versionParts[2]);
        const patch = parseInt(versionParts[3]) + 1;
        newVersion = `v${major}.${minor}.${patch}`;
      } else {
        newVersion = `v1.0.${Date.now()}`;
      }

      const batch = await TrainingBatch.create({
        name: `Auto-training-${newVersion}`,
        sampleCount: unusedCorrections.length,
        status: 'running',
        startedAt: new Date(),
        parameters: {
          minSamples: MIN_TRAINING_SAMPLES,
          autoGenerated: true,
          source: 'scheduler'
        }
      });

      console.log(`[Scheduler] Created training batch ${batch.id} with ${unusedCorrections.length} samples`);

      const correctionsData = unusedCorrections.map(c => ({
        subtitle_index: c.subtitleIndex,
        original_start: c.originalStart,
        original_end: c.originalEnd,
        corrected_start: c.correctedStart,
        corrected_end: c.correctedEnd,
        original_text: c.originalText,
        vad_start: c.vadStart,
        vad_end: c.vadEnd,
        metadata: c.metadata
      }));

      let modelData;
      try {
        const response = await axios.post(
          `${ALGORITHM_SERVICE_URL}/api/v1/train`,
          {
            corrections: correctionsData,
            version: newVersion,
            name: `Auto-trained model ${newVersion}`
          },
          { timeout: 600000 }
        );

        modelData = response.data;
        console.log(`[Scheduler] Training completed for version ${newVersion}`);

        const modelVersion = await ModelVersion.create({
          version: newVersion,
          name: modelData.name || `Model ${newVersion}`,
          description: modelData.model_data?.description || 'Auto-generated model',
          modelType: 'linear_regression',
          modelData: modelData.model_data,
          isActive: true,
          isDefault: false,
          trainingSampleCount: modelData.training_sample_count,
          validationAccuracy: modelData.validation_accuracy,
          avgOffsetError: modelData.avg_offset_error,
          trainedAt: new Date()
        });

        await batch.update({
          status: 'completed',
          completedAt: new Date(),
          modelVersionId: modelVersion.id,
          metrics: {
            validation_accuracy: modelData.validation_accuracy,
            avg_offset_error: modelData.avg_offset_error
          }
        });

        await SubtitleCorrection.update(
          { isUsedForTraining: true, trainingBatchId: batch.id },
          { where: { id: unusedCorrections.map(c => c.id) } }
        );

        console.log(
          `[Scheduler] Model ${newVersion} created successfully. ` +
          `Accuracy: ${(modelData.validation_accuracy * 100).toFixed(1)}%, ` +
          `Avg error: ${(modelData.avg_offset_error * 1000).toFixed(0)}ms`
        );

        return {
          success: true,
          modelVersion: newVersion,
          modelId: modelVersion.id,
          accuracy: modelData.validation_accuracy,
          avgError: modelData.avg_offset_error
        };

      } catch (error) {
        console.error('[Scheduler] Training failed:', error.message);
        
        await batch.update({
          status: 'failed',
          completedAt: new Date(),
          metrics: { error: error.message }
        });

        throw error;
      }

    } catch (error) {
      console.error('[Scheduler] Training check failed:', error.message);
      throw error;
    } finally {
      this.isRunning = false;
      await this.releaseLock();
    }
  }

  async triggerManualTraining(minSamplesOverride = null) {
    console.log('[Scheduler] Manual training triggered');
    return this.checkAndScheduleTraining();
  }

  getStatus() {
    return {
      isRunning: this.isRunning,
      schedule: TRAINING_CRON_SCHEDULE,
      minSamples: MIN_TRAINING_SAMPLES,
      algorithmServiceUrl: ALGORITHM_SERVICE_URL
    };
  }
}

const schedulerService = new SchedulerService();

export default schedulerService;
