global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'envoy-admin'
    static_configs:
      - targets: ['envoy:9901']
    metrics_path: '/stats/prometheus'

  - job_name: 'management-api'
    static_configs:
      - targets: ['management-api:8082']
    metrics_path: '/metrics'

  - job_name: 'envoy-ingress'
    static_configs:
      - targets: ['envoy:8080']
