[source.crates-io]
replace-with = "ustc"

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "link-arg=--initial-memory=67108864",
    "-C", "link-arg=--max-memory=268435456",
    "-C", "link-arg=-zstack-size=65536",
]
