# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\"B\n\x06Tensor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x03\x12\r\n\x05\x64type\x18\x04 \x01(\t\"M\n\nClientInfo\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61taset_size\x18\x02 \x01(\x05\x12\x16\n\x0etraining_steps\x18\x03 \x01(\x05\"\x9f\x01\n\x14UploadWeightsRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x05\x12\"\n\x07weights\x18\x03 \x03(\x0b\x32\x11.federated.Tensor\x12\x15\n\rsamples_count\x18\x04 \x01(\x05\x12\x12\n\ntrain_loss\x18\x05 \x01(\x02\x12\x16\n\x0etrain_accuracy\x18\x06 \x01(\x02\"Q\n\x15UploadWeightsResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rcurrent_round\x18\x03 \x01(\x05\"B\n\x16\x44ownloadWeightsRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rcurrent_round\x18\x02 \x01(\x05\"\x8e\x01\n\x17\x44ownloadWeightsResponse\x12\r\n\x05round\x18\x01 \x01(\x05\x12\"\n\x07weights\x18\x02 \x03(\x0b\x32\x11.federated.Tensor\x12\r\n\x05ready\x18\x03 \x01(\x08\x12\x13\n\x0bshould_stop\x18\x04 \x01(\x08\x12\x1c\n\x14global_model_version\x18\x05 \x01(\t\"<\n\x11StartRoundRequest\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x18\n\x10\x65xpected_clients\x18\x02 \x01(\x05\"6\n\x12StartRoundResponse\x12\x0f\n\x07started\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x93\x02\n\x10\x46\x65\x64\x65ratedService\x12R\n\rUploadWeights\x12\x1f.federated.UploadWeightsRequest\x1a .federated.UploadWeightsResponse\x12X\n\x0f\x44ownloadWeights\x12!.federated.DownloadWeightsRequest\x1a\".federated.DownloadWeightsResponse\x12Q\n\x12StartTrainingRound\x12\x1c.federated.StartRoundRequest\x1a\x1d.federated.StartRoundResponseB\x03\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\000'
  _globals['_TENSOR']._serialized_start=30
  _globals['_TENSOR']._serialized_end=96
  _globals['_CLIENTINFO']._serialized_start=98
  _globals['_CLIENTINFO']._serialized_end=175
  _globals['_UPLOADWEIGHTSREQUEST']._serialized_start=178
  _globals['_UPLOADWEIGHTSREQUEST']._serialized_end=337
  _globals['_UPLOADWEIGHTSRESPONSE']._serialized_start=339
  _globals['_UPLOADWEIGHTSRESPONSE']._serialized_end=420
  _globals['_DOWNLOADWEIGHTSREQUEST']._serialized_start=422
  _globals['_DOWNLOADWEIGHTSREQUEST']._serialized_end=488
  _globals['_DOWNLOADWEIGHTSRESPONSE']._serialized_start=491
  _globals['_DOWNLOADWEIGHTSRESPONSE']._serialized_end=633
  _globals['_STARTROUNDREQUEST']._serialized_start=635
  _globals['_STARTROUNDREQUEST']._serialized_end=695
  _globals['_STARTROUNDRESPONSE']._serialized_start=697
  _globals['_STARTROUNDRESPONSE']._serialized_end=751
  _globals['_FEDERATEDSERVICE']._serialized_start=754
  _globals['_FEDERATEDSERVICE']._serialized_end=1029
# @@protoc_insertion_point(module_scope)
