# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import federated_pb2 as federated__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in federated_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadWeights = channel.unary_unary(
                '/federated.FederatedService/UploadWeights',
                request_serializer=federated__pb2.UploadWeightsRequest.SerializeToString,
                response_deserializer=federated__pb2.UploadWeightsResponse.FromString,
                _registered_method=True)
        self.DownloadWeights = channel.unary_unary(
                '/federated.FederatedService/DownloadWeights',
                request_serializer=federated__pb2.DownloadWeightsRequest.SerializeToString,
                response_deserializer=federated__pb2.DownloadWeightsResponse.FromString,
                _registered_method=True)
        self.StartTrainingRound = channel.unary_unary(
                '/federated.FederatedService/StartTrainingRound',
                request_serializer=federated__pb2.StartRoundRequest.SerializeToString,
                response_deserializer=federated__pb2.StartRoundResponse.FromString,
                _registered_method=True)


class FederatedServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTrainingRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadWeights,
                    request_deserializer=federated__pb2.UploadWeightsRequest.FromString,
                    response_serializer=federated__pb2.UploadWeightsResponse.SerializeToString,
            ),
            'DownloadWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadWeights,
                    request_deserializer=federated__pb2.DownloadWeightsRequest.FromString,
                    response_serializer=federated__pb2.DownloadWeightsResponse.SerializeToString,
            ),
            'StartTrainingRound': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrainingRound,
                    request_deserializer=federated__pb2.StartRoundRequest.FromString,
                    response_serializer=federated__pb2.StartRoundResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'federated.FederatedService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('federated.FederatedService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/UploadWeights',
            federated__pb2.UploadWeightsRequest.SerializeToString,
            federated__pb2.UploadWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/DownloadWeights',
            federated__pb2.DownloadWeightsRequest.SerializeToString,
            federated__pb2.DownloadWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTrainingRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/federated.FederatedService/StartTrainingRound',
            federated__pb2.StartRoundRequest.SerializeToString,
            federated__pb2.StartRoundResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
