# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_service.proto\x12\x0cvideoservice\"v\n\x0e\x46\x61\x63\x65\x41nnotation\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x0e\n\x06gender\x18\x05 \x01(\t\x12\x0b\n\x03\x61ge\x18\x06 \x01(\x05\x12\x12\n\nconfidence\x18\x07 \x01(\x02\"G\n\x0c\x46rameRequest\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\x05\"u\n\rFrameResponse\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\x05\x12+\n\x05\x66\x61\x63\x65s\x18\x04 \x03(\x0b\x32\x1c.videoservice.FaceAnnotation2[\n\x0cVideoService\x12K\n\x0cProcessVideo\x12\x1a.videoservice.FrameRequest\x1a\x1b.videoservice.FrameResponse(\x01\x30\x01\x42\x03\x90\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\220\001\000'
  _globals['_FACEANNOTATION']._serialized_start=37
  _globals['_FACEANNOTATION']._serialized_end=155
  _globals['_FRAMEREQUEST']._serialized_start=157
  _globals['_FRAMEREQUEST']._serialized_end=228
  _globals['_FRAMERESPONSE']._serialized_start=230
  _globals['_FRAMERESPONSE']._serialized_end=347
  _globals['_VIDEOSERVICE']._serialized_start=349
  _globals['_VIDEOSERVICE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
